import type { Metadata } from "next";
import { DM_Serif_Display, DM_Sans } from "next/font/google";
import "./globals.css";

const dm_serif = DM_Serif_Display({
  subsets: ["latin"],
  style: "normal",
  weight: "400",
  variable: "--font-dm-serif",
})

const dm_sans = DM_Sans({
  subsets: ["latin"],
  style: "normal",
  weight: "variable",
  variable: "--font-dm",
})


  

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm_sans.className}>{children}</body>
    </html>
  );
}
